### ISSUE TITLE
Use with Windows?

### ISSUE THREAD

**Issue by HoLue** [horihiro/azure-functions-python-opencv-example#1]
Haw can I use this with windows? I should ".. install docker for windows and WSL with docker cli in order to get required files."
But how? Is there a good description anywhere?

**Comment by horihiro** [comment]
Yes you can use this with windows if you install docker daemon (docker for windows) and WSL in order to execute [retrieve_so.sh](https://github.com/horihiro/azure-functions-python-opencv-example/blob/master/retrieve_so.sh) file.

Please try the steps in [README.md](https://github.com/horihiro/azure-functions-python-opencv-example/blob/master/README.md).

Could you please let me know which step you cannot do if you have?

**Comment by horihiro** [comment]
I added bat file for retrieving so files.
So windows users don't need to use WSL.

**Comment by HoLue** [comment]
Thanks for providing the bat file!

**Comment by horihiro** [comment]
You're welcome,
But it seems that you don't need this as you know followings.
https://github.com/Azure/azure-functions-python-worker/issues/497
